import { Component, Input } from '@angular/core';
import {
  LucideAngularModule,
  LayoutDashboard,
  Users,
  ShieldCheck,
  Store,
  Tags,
  Utensils,
  CreditCard,
  UserRound,
  UploadCloud,
  Bell,
  Sun,
  Moon,
  LogOut,
  PanelLeftClose,
  PanelLeftOpen,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Plus,
  Search,
  SlidersHorizontal,
  ArrowUpRight,
  ArrowRight,
  RefreshCw,
  MoreHorizontal,
  Pencil,
  Trash2,
  Eye,
  X,
  Check,
  CheckCheck,
  CircleAlert,
  FileText,
  Image,
  Copy,
  Download,
  Menu,
  LockKeyhole,
  Mail,
  Globe,
  Activity,
  ExternalLink,
  KeyRound,
  LoaderCircle,
  Building2,
  CircleCheck,
  Clock3,
  FolderOpen,
} from 'lucide-angular';

const icons: Record<string, any> = {
  dashboard: LayoutDashboard,
  users: Users,
  roles: ShieldCheck,
  shops: Store,
  categories: Tags,
  genres: Utensils,
  'payment-methods': CreditCard,
  staffs: UserRound,
  upload: UploadCloud,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  logout: LogOut,
  collapse: PanelLeftClose,
  expand: PanelLeftOpen,
  down: ChevronDown,
  right: ChevronRight,
  left: ChevronLeft,
  plus: Plus,
  search: Search,
  filter: SlidersHorizontal,
  arrow: ArrowUpRight,
  forward: ArrowRight,
  refresh: RefreshCw,
  more: MoreHorizontal,
  edit: Pencil,
  delete: Trash2,
  eye: Eye,
  close: X,
  check: Check,
  read: CheckCheck,
  alert: CircleAlert,
  file: FileText,
  image: Image,
  copy: Copy,
  download: Download,
  menu: Menu,
  lock: LockKeyhole,
  mail: Mail,
  globe: Globe,
  activity: Activity,
  external: ExternalLink,
  key: KeyRound,
  loading: LoaderCircle,
  building: Building2,
  success: CircleCheck,
  clock: Clock3,
  folder: FolderOpen,
};

@Component({
  selector: 'app-icon',
  imports: [LucideAngularModule],
  template:
    '<lucide-icon [img]="icons[name] || icons[\'folder\']" [size]="size" [strokeWidth]="1.8" aria-hidden="true" />',
  host: { 'aria-hidden': 'true' },
})
export class Icon {
  @Input() name = 'folder';
  @Input() size = 20;
  readonly icons = icons;
}
